# This is a basic workflow to help you get started with Actions

name: MarketPlace Actions Test



# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
      input_value:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
      enableFeatureX:
        description: 'Enable feature X'
        required: false
        type: 'boolean'
        default: 'false'

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: node:16

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: nate-fidalgo/exampleaction@v1


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
